// File generated from our OpenAPI spec by Stainless.

package com.omnistack.api.models

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class ChatCompletionCreateResponseTest {

    @Test
    fun createChatCompletionCreateResponse() {
        val chatCompletionCreateResponse =
            ChatCompletionCreateResponse.builder()
                .id("id")
                .choices(
                    listOf(
                        ChatCompletionCreateResponse.Choice.builder()
                            .finishReason(ChatCompletionCreateResponse.Choice.FinishReason.STOP)
                            .index(123L)
                            .logprobs(
                                ChatCompletionCreateResponse.Choice.Logprobs.builder()
                                    .content(
                                        listOf(
                                            ChatCompletionCreateResponse.Choice.Logprobs.Content
                                                .builder()
                                                .token("token")
                                                .bytes(listOf(123L))
                                                .logprob(42.23)
                                                .topLogprobs(
                                                    listOf(
                                                        ChatCompletionCreateResponse.Choice.Logprobs
                                                            .Content
                                                            .TopLogprob
                                                            .builder()
                                                            .token("token")
                                                            .bytes(listOf(123L))
                                                            .logprob(42.23)
                                                            .build()
                                                    )
                                                )
                                                .build()
                                        )
                                    )
                                    .refusal(
                                        listOf(
                                            ChatCompletionCreateResponse.Choice.Logprobs.Refusal
                                                .builder()
                                                .token("token")
                                                .bytes(listOf(123L))
                                                .logprob(42.23)
                                                .topLogprobs(
                                                    listOf(
                                                        ChatCompletionCreateResponse.Choice.Logprobs
                                                            .Refusal
                                                            .TopLogprob
                                                            .builder()
                                                            .token("token")
                                                            .bytes(listOf(123L))
                                                            .logprob(42.23)
                                                            .build()
                                                    )
                                                )
                                                .build()
                                        )
                                    )
                                    .build()
                            )
                            .message(
                                ChatCompletionCreateResponse.Choice.Message.builder()
                                    .content("content")
                                    .refusal("refusal")
                                    .role(
                                        ChatCompletionCreateResponse.Choice.Message.Role.ASSISTANT
                                    )
                                    .functionCall(
                                        ChatCompletionCreateResponse.Choice.Message.FunctionCall
                                            .builder()
                                            .arguments("arguments")
                                            .name("name")
                                            .build()
                                    )
                                    .toolCalls(
                                        listOf(
                                            ChatCompletionCreateResponse.Choice.Message.ToolCall
                                                .builder()
                                                .id("id")
                                                .function(
                                                    ChatCompletionCreateResponse.Choice.Message
                                                        .ToolCall
                                                        .Function
                                                        .builder()
                                                        .arguments("arguments")
                                                        .name("name")
                                                        .build()
                                                )
                                                .type(
                                                    ChatCompletionCreateResponse.Choice.Message
                                                        .ToolCall
                                                        .Type
                                                        .FUNCTION
                                                )
                                                .build()
                                        )
                                    )
                                    .build()
                            )
                            .build()
                    )
                )
                .created(123L)
                .model("model")
                .object_(ChatCompletionCreateResponse.Object.CHAT_COMPLETION)
                .serviceTier(ChatCompletionCreateResponse.ServiceTier.SCALE)
                .systemFingerprint("system_fingerprint")
                .usage(
                    ChatCompletionCreateResponse.Usage.builder()
                        .completionTokens(123L)
                        .promptTokens(123L)
                        .totalTokens(123L)
                        .completionTokensDetails(
                            ChatCompletionCreateResponse.Usage.CompletionTokensDetails.builder()
                                .reasoningTokens(123L)
                                .build()
                        )
                        .build()
                )
                .build()
        assertThat(chatCompletionCreateResponse).isNotNull
        assertThat(chatCompletionCreateResponse.id()).isEqualTo("id")
        assertThat(chatCompletionCreateResponse.choices())
            .containsExactly(
                ChatCompletionCreateResponse.Choice.builder()
                    .finishReason(ChatCompletionCreateResponse.Choice.FinishReason.STOP)
                    .index(123L)
                    .logprobs(
                        ChatCompletionCreateResponse.Choice.Logprobs.builder()
                            .content(
                                listOf(
                                    ChatCompletionCreateResponse.Choice.Logprobs.Content.builder()
                                        .token("token")
                                        .bytes(listOf(123L))
                                        .logprob(42.23)
                                        .topLogprobs(
                                            listOf(
                                                ChatCompletionCreateResponse.Choice.Logprobs.Content
                                                    .TopLogprob
                                                    .builder()
                                                    .token("token")
                                                    .bytes(listOf(123L))
                                                    .logprob(42.23)
                                                    .build()
                                            )
                                        )
                                        .build()
                                )
                            )
                            .refusal(
                                listOf(
                                    ChatCompletionCreateResponse.Choice.Logprobs.Refusal.builder()
                                        .token("token")
                                        .bytes(listOf(123L))
                                        .logprob(42.23)
                                        .topLogprobs(
                                            listOf(
                                                ChatCompletionCreateResponse.Choice.Logprobs.Refusal
                                                    .TopLogprob
                                                    .builder()
                                                    .token("token")
                                                    .bytes(listOf(123L))
                                                    .logprob(42.23)
                                                    .build()
                                            )
                                        )
                                        .build()
                                )
                            )
                            .build()
                    )
                    .message(
                        ChatCompletionCreateResponse.Choice.Message.builder()
                            .content("content")
                            .refusal("refusal")
                            .role(ChatCompletionCreateResponse.Choice.Message.Role.ASSISTANT)
                            .functionCall(
                                ChatCompletionCreateResponse.Choice.Message.FunctionCall.builder()
                                    .arguments("arguments")
                                    .name("name")
                                    .build()
                            )
                            .toolCalls(
                                listOf(
                                    ChatCompletionCreateResponse.Choice.Message.ToolCall.builder()
                                        .id("id")
                                        .function(
                                            ChatCompletionCreateResponse.Choice.Message.ToolCall
                                                .Function
                                                .builder()
                                                .arguments("arguments")
                                                .name("name")
                                                .build()
                                        )
                                        .type(
                                            ChatCompletionCreateResponse.Choice.Message.ToolCall
                                                .Type
                                                .FUNCTION
                                        )
                                        .build()
                                )
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(chatCompletionCreateResponse.created()).isEqualTo(123L)
        assertThat(chatCompletionCreateResponse.model()).isEqualTo("model")
        assertThat(chatCompletionCreateResponse.object_())
            .isEqualTo(ChatCompletionCreateResponse.Object.CHAT_COMPLETION)
        assertThat(chatCompletionCreateResponse.serviceTier())
            .isEqualTo(ChatCompletionCreateResponse.ServiceTier.SCALE)
        assertThat(chatCompletionCreateResponse.systemFingerprint()).isEqualTo("system_fingerprint")
        assertThat(chatCompletionCreateResponse.usage())
            .isEqualTo(
                ChatCompletionCreateResponse.Usage.builder()
                    .completionTokens(123L)
                    .promptTokens(123L)
                    .totalTokens(123L)
                    .completionTokensDetails(
                        ChatCompletionCreateResponse.Usage.CompletionTokensDetails.builder()
                            .reasoningTokens(123L)
                            .build()
                    )
                    .build()
            )
    }
}
